name: CMake

on:
  push

env:
  BUILD_TYPE: Release

jobs:
  hf1-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1

    - name: Configure CMake for HF1
      run: cmake ./HF1 -B ${{github.workspace}}/HF1/build

    - name: Build HF1
      run: cmake --build ${{github.workspace}}/HF1/build

    - name: Configure CMake for HF2
      run: cmake ./HF2 -B ${{github.workspace}}/HF2/build

    - name: Build HF2
      run: cmake --build ${{github.workspace}}/HF2/build