name: CMake

on:
  push

env:
  BUILD_TYPE: Release

jobs:
  hf1-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1

    - name: Go to HF1
      run: cd HF1

    - name: wtf
      run: ls -la

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/HF1/build

    - name: Build
      run: cmake --build ${{github.workspace}}/HF1/build

  hf2-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1

    - name: Go to HF2
      run: cd HF2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/HF2/build

    - name: Build
      run: cmake --build ${{github.workspace}}/HF2/build
