name: CMake

on:
  push

env:
  BUILD_TYPE: Release

jobs:
  hf1-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1

    - name: Go to HF1
      run: cd HF1

#    - name: Configure CMake
#      run: cmake ./HF1 -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake ./HF1 --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  hf2-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1

    - name: Go to HF2
      run: cd HF2

    - name: Configure CMake
      run: cmake ./HF2 -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake ./HF2 --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
